---
- name: deploy project-fullstack to k8s
  hosts: k8s-master
  become: true
  tasks:
    - name: copy deploy yaml file to k8s-master
      copy:
        src: ./kubernetes
        dest: /tmp/
    - name: run porject-fullstack pods and service
      shell:  |
          export TAG={{tag}}
          envsubst < /tmp/kubernetes/frontend-react-js-deployment.yaml | kubectl apply -f -
          envsubst < /tmp/kubernetes/backend-flask-deployment.yaml | kubectl apply -f -
          kubectl apply -f /tmp/kubernetes/aminebootcamp-default-networkpolicy.yaml
          kubectl apply -f /tmp/kubernetes/backend-flask-claim0-persistentvolumeclaim.yaml
          kubectl apply -f /tmp/kubernetes/backend-flask-service.yaml
          kubectl apply -f /tmp/kubernetes/db-deployment.yaml
          kubectl apply -f /tmp/kubernetes/db-persistentvolumeclaim.yaml
          kubectl apply -f /tmp/kubernetes/db-service.yaml
          kubectl apply -f /tmp/kubernetes/frontend-react-js-claim0-persistentvolumeclaim.yaml
          kubectl apply -f /tmp/kubernetes/frontend-react-js-service.yaml
          kubectl apply -f /tmp/kubernetes/xray-daemon-deployment.yaml
          kubectl apply -f /tmp/kubernetes/xray-daemon-service.yaml


