apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-react-js
  name: frontend-react-js
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-react-js
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/aminebootcamp-default: "true"
        io.kompose.service: frontend-react-js
    spec:
      containers:
        - image: medamine77/frontend-react-js:$TAG           # pull from dockerhub
          name: frontend-react-js
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /frontend-react-js
              name: frontend-react-js-claim0
      restartPolicy: Always
      volumes:
        - name: frontend-react-js-claim0
          persistentVolumeClaim:
            claimName: frontend-react-js-claim0
status: {}
